### ISSUE TITLE
OSError: stabilityai/stable-diffusion-2-1-base does not appear to have a file named scheduler_config.json.

### ISSUE THREAD

**Issue by wangzhen-ing** [MichalGeyer/pnp-diffusers#3]
how to solve this problem
I tried `pip install --upgrade transformers`, But it doesn't work!

**Comment by wangzhen-ing** [comment]
Is this issue related to the network?

**Comment by henbucuoshanghai** [comment]
how to slove it?

**Comment by wangzhen-ing** [comment]
> how to slove it?

It may be due to the network, so you need to download all the required files locally.
